---
title: "NQC Probs"
format: html
---

Load in packages and read in data:

```{r}
library(duckdb)
library(tidyverse)
con <- dbConnect(duckdb())
tbl_pointer <- tbl(con, "read_parquet('CAISO_dam_big.parquet')")
nqc <- list(
  `2023` = readxl::read_excel("NQC_2023.xls", sheet = "2023 NQC List"),
  `2024` = readxl::read_excel("NQC_2024_sorted.xlsx"),
  `2025` = readxl::read_excel("NQC_2025.xlsx", sheet = "2025 NQC List"),
  `2026` = readxl::read_excel("NQC_2026.xlsx", sheet = "2026 NQC List")
) |>
  imap(\(x, year) {
    x |>
      select(`Generator Name`:DEC) |>
      pivot_longer(JAN:DEC, names_to = "month", values_to = "capacity") |>
      mutate(year = as.integer(year), .before = month)
  }) |>
  list_rbind()
```

Get max capacity for each year/month, each id:

```{r}
observed_max <- tbl_pointer |>
  filter(
    !is.na(SCH_BID_XAXISDATA),
    RESOURCE_TYPE == "GENERATOR",
    MARKETPRODUCTTYPE == "EN"
  ) |>
  mutate(
    year = year(as.Date(STARTTIME)),
    month = month(as.Date(STARTTIME))
  ) |>
  slice_max(
    order_by = SCH_BID_XAXISDATA,
    n = 1,
    with_ties = FALSE,
    by = c(RESOURCEBID_SEQ, year, month)
  ) |>
  select(RESOURCEBID_SEQ, year, month, SCH_BID_XAXISDATA) |>
  collect()
```

Compare observed max capacity to NQC:

```{r}
check_capacity <- function(id, obs_max, obs_year, obs_month, nqc_data) {
  nqc_data |>
    filter(
      year == obs_year,
      month == str_to_upper(month.abb[obs_month]),
      capacity >= obs_max
    ) |>
    transmute(
      generator = `Generator Name`,
      capacity,
      prob = 1 / n(),
      id = id,
      year = obs_year,
      month = obs_month
    )
}

check_capacity(952796, 880, 2024, 6, nqc)
```

Repeat for all ids:

```{r}
check_probs <- function(obs_max_df) {
  obs_max_df |>
    pmap(
      \(RESOURCEBID_SEQ, year, month, SCH_BID_XAXISDATA) {
        check_capacity(RESOURCEBID_SEQ, SCH_BID_XAXISDATA, year, month, nqc)
      },
      .progress = TRUE
    ) |>
    list_rbind()
}

tibble(
  RESOURCEBID_SEQ = c(952796, 525442),
  year = c(2024, 2024),
  month = c(6, 2),
  SCH_BID_XAXISDATA = c(880, 120)
) |>
  check_probs()

nqc_all <- observed_max |>
  check_probs() |>
  arrow::write_parquet(nqc_all, "NQC_data_all.parquet")
```

```{r}
nqc_all |>
  summarize(total = first(prob) * n_distinct(id), .by = c(year, month, prob)) |>
  summarize(total = max(total), .by = c(year, month)) |>
  arrange(year, month)
```
