---
title: "Bid Curves"
format: html
---


```{r}
library(tidyverse)
```


```{r}
data <- read_csv(here::here("20250701_20250701_PUB_BID_DAM_v3.csv"))
subset <- data |>
  select(STARTTIME, STOPTIME, RESOURCE_TYPE, SCHEDULINGCOORDINATOR_SEQ, RESOURCEBID_SEQ,
         MARKETPRODUCTTYPE, SELFSCHEDMW, SCH_BID_XAXISDATA, SCH_BID_Y1AXISDATA) |>
  mutate(STARTDATETIME = as.factor(STARTTIME),
         STARTTIME = hms::as_hms(STARTTIME))
  # mutate(STARTDATE = date(STARTTIME),
  #        STOPDATE = date(STOPTIME),
  #        STARTTIME = hms::as_hms(STARTTIME),
  #        STOPTIME = hms::as_hms(STOPTIME))
```

```{r}
subset |>
  filter(RESOURCEBID_SEQ == 394840,
         STARTTIME %in% c(hms::as_hms("00:00:00"),
                          hms::as_hms("08:00:00"),
                          hms::as_hms("10:00:00"),
                          hms::as_hms("11:00:00"),
                          hms::as_hms("12:00:00"))) |>
  ggplot(aes(x=SCH_BID_XAXISDATA, y=SCH_BID_Y1AXISDATA, 
             color = STARTDATETIME, group=STARTDATETIME)) +
  geom_line() +
  geom_point()
```


```{r}
plot_curves <- function(market_data, resource_id){
    date <- as.Date(market_data$STARTTIME[1])

    plot <- market_data |>
        mutate(STARTDATETIME = as.factor(STARTTIME),
               STARTTIME = hms::as_hms(STARTTIME)) |>
        filter(RESOURCEBID_SEQ == resource_id)|>
              # STARTTIME %in% hms::as_hms("14:00:00")) |>
       #  STARTTIME %in% c(hms::as_hms("00:00:00"),
       #                    hms::as_hms("04:00:00"),
       #                    hms::as_hms("08:00:00"),
       #                    hms::as_hms("13:00:00"),
       #                    hms::as_hms("20:00:00"))) |>
        ggplot(aes(x=SCH_BID_XAXISDATA, y=SCH_BID_Y1AXISDATA, 
             color = STARTDATETIME, group=STARTDATETIME)) +
        geom_line() +
        geom_point() +
       #  xlim(-Inf, Inf) +
        labs(
            x="Quantity (MW)",
            y = "Bid Price ($/MWh)",
            title = sprintf("ID: %s Date: %s", resource_id, date)) +
        theme_minimal()
       plot
}

plot_curves(data, 394840)
```

```{r}
sept14 <- read_csv(here::here("plot data", "20250914_20250914_PUB_BID_DAM_v3.csv"))
sept14plot <- plot_curves(sept14, 394840)
ggsave(here::here("plots", "sept14filter.png"))

oct01 <- read_csv(here::here("plot data", "20251001_20251001_PUB_BID_DAM_v3.csv"))
oct01plot <- plot_curves(oct10, 394840)
ggsave(here::here("plots", "oct01filter.png"))

oct14 <- read_csv(here::here("plot data","20251014_20251014_PUB_BID_DAM_v3.csv"))
oct14plot <- plot_curves(oct14, 394840)
ggsave(here::here("plots", "oct14filter.png"))

mar14 <- read_csv(here::here("plot data", "20250314_20250314_PUB_BID_DAM_v3.csv"))
mar14plot <- plot_curves(mar14, 394840)
ggsave(here::here("plots", "mar14filter.png"))
```

```{r}
sept14 |>
       mutate(STARTTIME = hms::as_hms(STARTTIME)) |>
       filter(RESOURCEBID_SEQ == 394840) |>
       filter(STARTTIME == hms::as_hms("16:00:00"))

test <- sept14 |>
       filter(RESOURCEBID_SEQ == 394840)
```

```{r}
# NAs in SCH_BID_XAXISDATA?
oct01 |>
  mutate(STARTTIME = hms::as_hms(STARTTIME)) |>
  filter(
    RESOURCEBID_SEQ == 394840,
#     STARTTIME %in% hms::as_hms(c("00:00:00","08:00:00","10:00:00","11:00:00","12:00:00"))
  ) |>
  filter(is.na(SCH_BID_XAXISDATA) | is.na(SCH_BID_Y1AXISDATA)) |>
  view()
#   select(STARTTIME, STARTDATETIME = STARTTIME, SCH_BID_XAXISDATA, SCH_BID_Y1AXISDATA)

```


```{r}
# area between curves plot
s14hr0 <- sept14 |>
       mutate(STARTDATETIME = as.factor(STARTTIME),
              STARTDATTE = as.Date(STARTDATETIME),
               STARTTIME = hms::as_hms(STARTTIME)) |>
       filter(RESOURCEBID_SEQ == 394840,
       STARTTIME == hms::as_hms("00:00:00"))

o01hr0 <- oct01 |>
       mutate(STARTDATETIME = as.factor(STARTTIME),
              STARTDATTE = as.Date(STARTDATETIME),
               STARTTIME = hms::as_hms(STARTTIME)) |>
       filter(RESOURCEBID_SEQ == 394840,
       STARTTIME == hms::as_hms("00:00:00"))

s14hr0 |>
       bind_rows(o01hr0) |>
       ggplot(aes(x=SCH_BID_XAXISDATA, y=SCH_BID_Y1AXISDATA,
       color = as.factor(STARTDATTE), group = STARTDATTE)) +
       geom_point() +
       geom_line() + 
       labs(color = 'Date',
       title = "RESOURCE ID: 394840") +
       theme_minimal() 
ggsave(here::here("plots","area-bw-curves.png"))
```

# NEW WAY TO PLOT DATA

```{r}
example <- subset |>
  filter(RESOURCEBID_SEQ == 394840,
         STARTTIME %in% c(hms::as_hms("00:00:00"),
                          hms::as_hms("08:00:00"),
                          hms::as_hms("10:00:00"),
                          hms::as_hms("11:00:00"),
                          hms::as_hms("12:00:00")),
         !is.na(SCH_BID_XAXISDATA)) |>
  arrange(STARTDATETIME, SCH_BID_XAXISDATA) |>
  group_by(STARTTIME) |>
  mutate(xend = lead(SCH_BID_XAXISDATA),
         yend = SCH_BID_Y1AXISDATA,
         yend = if_else(is.na(yend), SCH_BID_Y1AXISDATA, yend),
         xend = if_else(is.na(xend), SCH_BID_XAXISDATA, xend))

example |>
       ggplot(aes(x=SCH_BID_XAXISDATA, y=SCH_BID_Y1AXISDATA,
                  xend=xend, yend=yend, group=STARTTIME,color=STARTTIME
                  show.legend=TRUE)) +
       geom_point() +
       geom_segment() +
       geom_point(aes(x=xend, y=SCH_BID_Y1AXISDATA), shape=1) +
       labs() +
       theme_minimal()
```

```{r}
plot_curves_new <- function(market_data, resource_id){
       date <- as.Date(market_data$STARTTIME[1])
       plot <- market_data |>
              mutate(STARTDATETIME = as.factor(STARTTIME),
               STARTTIME = hms::as_hms(STARTTIME)) |>
              filter(RESOURCEBID_SEQ == resource_id,
                     !is.na(SCH_BID_XAXISDATA))|>
              arrange(STARTDATETIME, SCH_BID_XAXISDATA) |>
              group_by(STARTTIME) |>
              mutate(xend = lead(SCH_BID_XAXISDATA),
                     yend = SCH_BID_Y1AXISDATA,
                     # yend = if_else(is.na(yend), SCH_BID_Y1AXISDATA, yend),
                     xend = if_else(is.na(xend), SCH_BID_XAXISDATA, xend),
                     is_pos = if_else(SCH_BID_XAXISDATA  > 0, TRUE, FALSE),
                     end_point = (SCH_BID_XAXISDATA == xend),
                     single_point = (n() == 1))|>
              ggplot(aes(x=SCH_BID_XAXISDATA, y=SCH_BID_Y1AXISDATA,
                  xend=xend, yend=yend, group=STARTTIME,color=factor(STARTTIME))) +
              geom_point(aes(shape = ifelse(single_point, 2, ifelse(end_point, 1, 16)))) +
              scale_shape_identity() +
              geom_segment() +
              geom_point(aes(x=xend, y=SCH_BID_Y1AXISDATA), shape=1) +
              # geom_point(data = ~filter(.x, single_point == TRUE), shape = 17, size = 3) +
              # facet_wrap(~is_pos) +
              labs(x="Quantity (MW)",
                   y = "Bid Price ($/MWh)",
                   title = sprintf("ID: %s Date: %s", resource_id, date),
                   color="Hour") +
              theme_bw()
       plot
}
plot_curves_new(data, 140023)
plot_curves(data, 140023)
plot_curves_new(data, 204933)
```



```{r}
plot_curves_to_right <- function(market_data, resource_id){
       date_val <- as.Date(market_data$STARTTIME[1])
       
       plot_data <- market_data |>
              mutate(STARTDATETIME = as.factor(STARTTIME),
                     STARTTIME = hms::as_hms(STARTTIME)) |>
              filter(RESOURCEBID_SEQ == resource_id,
                     !is.na(SCH_BID_XAXISDATA)) |>
              arrange(STARTDATETIME, SCH_BID_XAXISDATA) |>
              group_by(STARTTIME) |>
              arrange(SCH_BID_XAXISDATA, .by_group = TRUE) |>
              mutate(xend = lag(SCH_BID_XAXISDATA),
                     yend = SCH_BID_Y1AXISDATA,
                     xend = if_else(is.na(xend), 0, xend),
                     xend = if_else(row_number() == 1 & (n() > 1), SCH_BID_XAXISDATA, xend),
                     # if using lead() then >= 0!!!
                     is_pos = if_else(SCH_BID_XAXISDATA  > 0, "Positive MW Bids", "Negative MW Bids"),
                     end_point = (SCH_BID_XAXISDATA == xend),
                     single_point = (n() == 1)
                     )
       plot_data |>
              ggplot(aes(x=SCH_BID_XAXISDATA, y=SCH_BID_Y1AXISDATA,
                     #     xend=xend, yend=yend, 
                         group=STARTTIME, color=factor(STARTTIME))) +
              geom_point(aes(
                     shape = ifelse(single_point, "Single-point bid",
                            ifelse(end_point, "End point", "Submitted bid")),
                     size = ifelse(single_point, 3, 1.5))) +
              scale_shape_manual(
                     name = "Point Type",
                     values = c(
                     "Single-point bid" = 17,  # triangle
                     "End point" = 1,          # hollow circle
                     "Submitted bid" = 16         # filled circle
                     ), drop=FALSE
              ) +
              # geom_point(aes(
              #     shape = ifelse(single_point, 17, ifelse(end_point, 1, 16)),
              #     size = ifelse(single_point, 3, 1.5)
              # )) +
              # scale_shape_identity() +
              scale_size_identity() + 
              geom_segment(aes(xend=xend, yend=yend), na.rm = TRUE) +
              geom_point(aes(x=xend, y=SCH_BID_Y1AXISDATA), shape=1, size=1.5) +
              labs(x="Quantity (MW)",
                   y = "Bid Price ($/MWh)",
                   title = sprintf("ID: %s Date: %s", resource_id, date_val),
                   color="Hour") +
              facet_wrap(~is_pos) +
              theme_bw()
       # return(plot_data)
}
# plot_curves_new(data, 394840)
# plot_curves_new(data, 160605)
# plot_curves_new(ex.data, 394840)
# plot_curves_new(data, 238485)
# plot_curves_new(data, 140023)
plot_curves_to_right(data, 204933)
```


```{r}
ex.data <- data |>
              filter(RESOURCEBID_SEQ == 394840,
              hms::as_hms(STARTTIME) %in% c(
                     # hms::as_hms("00:00:00"),
                     #      hms::as_hms("04:00:00"),
                     #      hms::as_hms("08:00:00"),
                          hms::as_hms("13:00:00")
                     #      hms::as_hms("20:00:00")
                          ),
              SCH_BID_XAXISDATA >= 0)
plot_curves_new(ex.data, 394840)

ex.data2 <- data |>
              filter(RESOURCEBID_SEQ == 140023,
              hms::as_hms(STARTTIME) %in% c(
                     hms::as_hms("18:00:00"),
                     hms::as_hms("15:00:00"),
                     hms::as_hms("09:00:00")))
              # SCH_BID_XAXISDATA >= 0)
test <- plot_curves_new(ex.data2, 140023) |>
       select(STARTTIME, SCH_BID_XAXISDATA, SCH_BID_Y1AXISDATA)
plot_curves_new(data, 140023)
test2 <- test |>
       select(STARTTIME, SCH_BID_XAXISDATA, xend, yend, SCH_BID_Y1AXISDATA)
test <- data |>
              filter(RESOURCEBID_SEQ == 394840) |>
              arrange(STARTTIME, SCH_BID_XAXISDATA) |>
              group_by(STARTTIME) |>
              mutate(n = n())

test <- data |>
              mutate(STARTDATETIME = as.factor(STARTTIME),
                     STARTTIME = hms::as_hms(STARTTIME)) |>
              filter(RESOURCEBID_SEQ == 238485,
                     !is.na(SCH_BID_XAXISDATA)) |>
              arrange(STARTDATETIME, SCH_BID_XAXISDATA) |>
              group_by(STARTTIME) |>
              mutate(xend = lead(SCH_BID_XAXISDATA),
                     yend = SCH_BID_Y1AXISDATA,
                     xend = if_else(is.na(xend), SCH_BID_XAXISDATA, xend),
                     is_pos = (SCH_BID_XAXISDATA  > 0),
                     end_point = (SCH_BID_XAXISDATA == xend),
                     single_point = (n() == 1)) |>
              select(STARTTIME, xend, yend, SCH_BID_XAXISDATA,SCH_BID_Y1AXISDATA)
```


```{r}
plot_curves_to_left <- function(market_data, resource_id){
       date_val <- as.Date(market_data$STARTTIME[1])
       
       plot_data <- market_data |>
              mutate(STARTDATETIME = as.factor(STARTTIME),
                     STARTTIME = hms::as_hms(STARTTIME)) |>
              filter(RESOURCEBID_SEQ == resource_id,
                     !is.na(SCH_BID_XAXISDATA)) |>
              arrange(STARTDATETIME, SCH_BID_XAXISDATA) |>
              group_by(STARTTIME) |>
              arrange(SCH_BID_XAXISDATA, .by_group = TRUE) |>
              mutate(xend = lag(SCH_BID_XAXISDATA),
                     yend = SCH_BID_Y1AXISDATA,
                     xend = if_else(is.na(xend), 0, xend),
                     xend = if_else(row_number() == 1 & (n() > 1), SCH_BID_XAXISDATA, xend),
                     # if using lead() then >= 0!!!
                     is_pos = if_else(SCH_BID_XAXISDATA  > 0, "Positive MW Bids", "Negative MW Bids"),
                     end_point = (SCH_BID_XAXISDATA == xend),
                     single_point = (n() == 1)
                     )
       plot_data |>
              ggplot(aes(x=SCH_BID_XAXISDATA, y=SCH_BID_Y1AXISDATA,
                     #     xend=xend, yend=yend, 
                         group=STARTTIME, color=factor(STARTTIME))) +
              geom_point(aes(
                     shape = ifelse(single_point, "Single-point bid",
                            ifelse(end_point, "End point", "Submitted bid")),
                     size = ifelse(single_point, 3, 1.5))) +
              scale_shape_manual(
                     name = "Point Type",
                     values = c(
                     "Single-point bid" = 17,  # triangle
                     "End point" = 1,          # hollow circle
                     "Submitted bid" = 16         # filled circle
                     ), drop=FALSE
              ) +
              # geom_point(aes(
              #     shape = ifelse(single_point, 17, ifelse(end_point, 1, 16)),
              #     size = ifelse(single_point, 3, 1.5)
              # )) +
              # scale_shape_identity() +
              scale_size_identity() + 
              geom_segment(aes(xend=xend, yend=yend), na.rm = TRUE) +
              geom_point(aes(x=xend, y=SCH_BID_Y1AXISDATA), shape=1, size=1.5) +
              labs(x="Quantity (MW)",
                   y = "Bid Price ($/MWh)",
                   title = sprintf("ID: %s Date: %s", resource_id, date_val),
                   color="Hour") +
              facet_wrap(~is_pos) +
              theme_bw()
       # return(plot_data)
}
```