library(tidyverse)
library(httr)
library(mirai)

# Partially generated by LLM.
# ! WILL NOT WORK ON WINDOWS DUE TO HOW LIBCURL WORKS
# (at the very least, not working for me)

#' Fetch CAISO OASIS DAM bid data by day. Only the first
#' 3 arguments are required to be set manually.
#'
#' @param start_date Start date (YYYY-MM-DD).
#' @param end_date End date (YYYY-MM-DD).
#' @param market Market type, either "RTM" or "DAM".
#' @param skip_existing Skip dates that already have a parquet on disk.
#' @param request_pause Seconds to sleep after each request.
#' @param retry_times Number of retries for transient failures.
#' @param retry_pause_base Base seconds between retries.
#' @param retry_pause_cap Max seconds between retries.
#' @return A tibble of OASIS DAM bid data.
fetch_oasis_prices <- function(
  start_date,
  end_date,
  market = c("RTM", "DAM"),
  skip_existing = TRUE,
  request_pause = 5,
  retry_times = 15,
  retry_pause_base = 3,
  retry_pause_cap = 20
) {
  market <- match.arg(market)

  temp_dir <- tempfile("oasis_")
  dir.create(temp_dir)
  on.exit(unlink(temp_dir, recursive = TRUE), add = TRUE)

  output_dir_name <- sprintf("CAISO_%s_daily", tolower(market))
  output_dir <- here::here(output_dir_name)
  dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)

  all_dates <- seq(
    lubridate::ymd(start_date),
    lubridate::ymd(end_date),
    by = "day"
  )

  if (isTRUE(skip_existing)) {
    existing_dates <- list.files(output_dir, pattern = "\\.parquet$") |>
      stringr::str_remove("\\.parquet$") |>
      lubridate::ymd(quiet = TRUE)

    existing_dates <- existing_dates[!is.na(existing_dates)]
    all_dates <- setdiff(all_dates, existing_dates)
  }

  if (length(all_dates) == 0) {
    return(tibble::tibble())
  }

  mirai::mirai_map(
    all_dates,
    function(d) {
      fetch_one(
        date = d,
        temp_dir = temp_dir,
        market = market,
        request_pause = request_pause,
        retry_times = retry_times,
        retry_pause_base = retry_pause_base,
        retry_pause_cap = retry_pause_cap
      ) |>
        arrow::write_parquet(
          here::here(
            output_dir_name,
            sprintf("%s.parquet", format(lubridate::as_date(d), "%Y%m%d"))
          )
        )
    },
    fetch_one = fetch_one
  )[.progress] |>
    purrr::list_rbind()
}

fetch_one <- function(
  date,
  temp_dir,
  market,
  request_pause,
  retry_times,
  retry_pause_base,
  retry_pause_cap
) {
  start_datetime <- date |>
    lubridate::as_date() |>
    lubridate::ymd(tz = "America/Los_Angeles") |>
    lubridate::with_tz("UTC") |>
    format("%Y%m%dT%H:%M-0000")

  temp_zip <- tempfile(fileext = ".zip", tmpdir = temp_dir)

  url <- httr::modify_url(
    "https://oasis.caiso.com/oasisapi/GroupZip",
    query = list(
      resultformat = 6,
      version = 3,
      groupid = sprintf("PUB_%s_GRP", market),
      startdatetime = start_datetime
    )
  )

  Sys.sleep(request_pause)

  response <- httr::RETRY(
    "GET",
    url,
    httr::user_agent("Mozilla/5.0"),
    httr::config(http_version = 1),
    httr::write_disk(temp_zip, overwrite = TRUE),
    times = retry_times,
    pause_base = retry_pause_base,
    pause_cap = retry_pause_cap
  )
  httr::stop_for_status(response)

  unzipped_files <- unzip(temp_zip, exdir = temp_dir)
  bid_pattern <- sprintf("PUB_BID_%s", market)
  bid_files <- unzipped_files |>
    purrr::keep(\(f) stringr::str_detect(basename(f), bid_pattern))

  if (length(bid_files) == 0) {
    warning(sprintf("No %s files found for %s", bid_pattern, date))
    return(tibble::tibble())
  }

  bid_files |>
    purrr::map(\(f) readr::read_csv(f, show_col_types = FALSE)) |>
    purrr::list_rbind()
}
