library(tidyverse)
library(httr)

# Partially generated by LLM.
# ! WILL NOT WORK ON WINDOWS DUE TO HOW LIBCURL WORKS
# (at the very least, not working for me)

#' Fetch CAISO OASIS DAM bid data by day. Only the first
#' 3 arguments are required to be set manually.
#'
#' @param start_date Start date (YYYY-MM-DD).
#' @param end_date End date (YYYY-MM-DD).
#' @param market Market type, either "RTM" or "DAM".
#' @param request_pause Seconds to sleep after each request.
#' @param retry_times Number of retries for transient failures.
#' @param retry_pause_base Base seconds between retries.
#' @param retry_pause_cap Max seconds between retries.
#' @return A tibble of OASIS DAM bid data.
fetch_oasis_prices <- function(
  start_date,
  end_date,
  market = c("RTM", "DAM"),
  request_pause = 5,
  retry_times = 15,
  retry_pause_base = 3,
  retry_pause_cap = 20
) {
  market <- match.arg(market)

  temp_dir <- tempfile("oasis_")
  dir.create(temp_dir)
  on.exit(unlink(temp_dir, recursive = TRUE), add = TRUE)

  seq(ymd(start_date), ymd(end_date), by = "day") |>
    # Could swap to mirai_map for parallelization
    map(\(d) {
      fetch_one(
        date = d,
        temp_dir = temp_dir,
        market = market,
        request_pause = request_pause,
        retry_times = retry_times,
        retry_pause_base = retry_pause_base,
        retry_pause_cap = retry_pause_cap
      )
    }) |>
    list_rbind()
}

fetch_one <- function(
  date,
  temp_dir,
  market,
  request_pause,
  retry_times,
  retry_pause_base,
  retry_pause_cap
) {
  start_datetime <- date |>
    as_date() |>
    ymd(tz = "America/Los_Angeles") |>
    with_tz("UTC") |>
    format("%Y%m%dT%H:%M-0000")

  temp_zip <- tempfile(fileext = ".zip", tmpdir = temp_dir)

  url <- modify_url(
    "https://oasis.caiso.com/oasisapi/GroupZip",
    query = list(
      resultformat = 6,
      version = 3,
      groupid = sprintf("PUB_%s_GRP", market),
      startdatetime = start_datetime
    )
  )

  Sys.sleep(request_pause)

  response <- RETRY(
    "GET",
    url,
    user_agent("Mozilla/5.0"),
    config(http_version = 1),
    write_disk(temp_zip, overwrite = TRUE),
    times = retry_times,
    pause_base = retry_pause_base,
    pause_cap = retry_pause_cap
  )
  stop_for_status(response)

  unzipped_files <- unzip(temp_zip, exdir = temp_dir)
  bid_pattern <- sprintf("PUB_BID_%s", market)
  bid_files <- unzipped_files |> keep(\(f) str_detect(basename(f), bid_pattern))

  if (length(bid_files) == 0) {
    warning(sprintf("No %s files found for %s", bid_pattern, date))
    return(tibble())
  }

  bid_files |> map(\(f) read_csv(f, show_col_types = FALSE)) |> list_rbind()
}
