library(tidyverse)
library(httr)

# Partially generated by LLM.
# ! WILL NOT WORK ON WINDOWS DUE TO HOW LIBCURL WORKS
# (at the very least, not working for me)

#' Fetch CAISO OASIS prices by month.
#'
#' Uses sequential requests with backoff and pause-based rate limiting.
#'
#' @param start_date Start date (YYYY-MM-DD).
#' @param end_date End date (YYYY-MM-DD). Used as the final monthly boundary.
#' @param market Market type, either "RTM" or "DAM".
#' @param request_pause Seconds to sleep after each request.
#' @param retry_times Number of retries for transient failures.
#' @param retry_pause_base Base seconds between retries.
#' @param retry_pause_cap Max seconds between retries.
#' @return A tibble of OASIS price data.
fetch_oasis_prices <- function(
  start_date,
  end_date,
  market = c("RTM", "DAM"),
  request_pause = 5,
  retry_times = 15,
  retry_pause_base = 3,
  retry_pause_cap = 20
) {
  market <- match.arg(market)
  nodes <- switch(
    market,
    RTM = "DLAP_PACE_NPM-APND,DLAP_PACW_NPM-APND,DLAP_PGAE-APND,DLAP_SCE-APND,DLAP_SDGE-APND,DLAP_VEA-APND",
    DAM = "DLAP_PGAE-APND,DLAP_SCE-APND,DLAP_SDGE-APND,DLAP_VEA-APND"
  )

  spec <- switch(
    market,
    RTM = list(queryname = "PRC_INTVL_LMP", version = 3, market_run_id = "RTM"),
    DAM = list(queryname = "PRC_LMP", version = 12, market_run_id = "DAM")
  )

  col_types <- switch(
    market,
    RTM = cols(
      INTERVALSTARTTIME_GMT = col_datetime(),
      INTERVALENDTIME_GMT = col_datetime(),
      OPR_DT = col_date(),
      OPR_HR = col_character(),
      NODE_ID_XML = col_character(),
      NODE_ID = col_character(),
      NODE = col_character(),
      MARKET_RUN_ID = col_character(),
      LMP_TYPE = col_character(),
      XML_DATA_ITEM = col_character(),
      PNODE_RESMRID = col_character(),
      GRP_TYPE = col_character(),
      POS = col_double(),
      VALUE = col_double(),
      OPR_INTERVAL = col_double(),
      GROUP = col_double()
    ),
    DAM = cols(
      INTERVALSTARTTIME_GMT = col_datetime(),
      INTERVALENDTIME_GMT = col_datetime(),
      OPR_DT = col_date(),
      OPR_HR = col_double(),
      OPR_INTERVAL = col_double(),
      NODE_ID_XML = col_character(),
      NODE_ID = col_character(),
      NODE = col_character(),
      MARKET_RUN_ID = col_character(),
      LMP_TYPE = col_character(),
      XML_DATA_ITEM = col_character(),
      PNODE_RESMRID = col_character(),
      GRP_TYPE = col_character(),
      POS = col_double(),
      MW = col_double(),
      GROUP = col_double()
    )
  )

  dates <- seq.Date(as.Date(start_date), as.Date(end_date), by = "month")
  start_dates <- dates[-length(dates)]
  end_dates <- dates[-1]
  temp_dir <- tempfile("oasis_")
  dir.create(temp_dir)
  on.exit(unlink(temp_dir, recursive = TRUE), add = TRUE)

  map2(
    start_dates,
    end_dates,
    \(start, end) {
      fetch_one(
        start_date = start,
        end_date = end,
        spec = spec,
        nodes = nodes,
        col_types = col_types,
        temp_dir = temp_dir,
        request_pause = request_pause,
        retry_times = retry_times,
        retry_pause_base = retry_pause_base,
        retry_pause_cap = retry_pause_cap
      )
    }
  ) |>
    list_rbind()
}

#' Fetch one month of CAISO OASIS prices.
#'
#' Internal helper for `fetch_oasis_prices()`.
#'
#' @param start_date Start date for the month.
#' @param end_date End date for the month.
#' @param spec List with queryname, version, and market_run_id.
#' @param nodes Comma-separated node list.
#' @param request_pause Seconds to sleep after each request.
#' @param retry_times Number of retries for transient failures.
#' @param retry_pause_base Base seconds between retries.
#' @param retry_pause_cap Max seconds between retries.
#' @return A tibble for a single month of prices.
#' @keywords internal
fetch_one <- function(
  start_date,
  end_date,
  spec,
  nodes,
  col_types,
  temp_dir,
  request_pause,
  retry_times,
  retry_pause_base,
  retry_pause_cap
) {
  start_datetime <- paste0(format(start_date, "%Y%m%d"), "T08:00-0000")
  end_datetime <- paste0(format(end_date, "%Y%m%d"), "T07:00-0000")
  temp <- tempfile(tmpdir = temp_dir)

  url <- modify_url(
    "https://oasis.caiso.com/oasisapi/SingleZip",
    query = list(
      resultformat = 6,
      queryname = spec$queryname,
      version = spec$version,
      startdatetime = start_datetime,
      enddatetime = end_datetime,
      market_run_id = spec$market_run_id,
      node = nodes
    )
  )

  req_config <- config(http_version = 1)
  ua <- user_agent("Mozilla/5.0 (Windows NT 10.0; Win64; x64)")
  if (request_pause > 0) {
    Sys.sleep(request_pause)
  }

  response <- RETRY(
    "GET",
    url,
    ua,
    req_config,
    write_disk(temp, overwrite = TRUE),
    times = retry_times,
    pause_base = retry_pause_base,
    pause_cap = retry_pause_cap
  )

  stop_for_status(response)
  unzip(temp, exdir = tempdir()) |>
    read_csv(col_types = col_types)
}
